### ISSUE TITLE
Off Topic

### ISSUE THREAD

**Issue by dedovsky** [0Supa/okeybot#115]
Sorry for off topic, but i wanna ask u a question:
did you make the kappa.lol, femboy.beauty, gachi.gay sites?

**Comment by 0Supa** [comment]
Yes, as you can see on my website.

**Comment by dedovsky** [comment]
can u give me whole list of these sites? Are there other sites like this?

**Comment by 0Supa** [comment]
The domains you listed above are the only ones I manage.
Please refrain from making any other off-topic comments or issues, this is not a place for direct contact.
