### ISSUE TITLE
Suggestion (?lines today)

### ISSUE THREAD

**Issue by lucas19961** [0Supa/okeybot#34]
Hey, can you please make a Command where users can check their own lines from today? Sorry for writing the suggestion under Issues

**Comment by lucas19961** [comment]
And maybe change the command randline so Users can check randlines from users in other logged channels (?rl user1 channel1)

**Comment by Julia-Roman** [comment]
The `?lines` command return message will now include the number of messages sent today by the specified user: 5fd1edb0c46ca4549d35ec1f85d485ee14c9bb4d

**Comment by lucas19961** [comment]
Maybe something like ?lines user channel ? so I can check my lines in other channel @0Supa
